# Generated by Django 5.2.4 on 2025-07-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('token_blacklist', '0013_alter_blacklistedtoken_options_and_more'),
        ('users', '0006_rename_users_jusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JUsers',
            new_name='Users',
        ),
    ]
