# Generated by Django 5.2.4 on 2025-07-30 16:13

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_jusers_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv_file',
            field=models.FileField(upload_to='cvs/', validators=[users.models.validate_pdf]),
        ),
    ]
