# Generated by Django 5.2.4 on 2025-07-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('description_text', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salary_formatted', models.CharField(blank=True, max_length=100, null=True)),
                ('company_rating', models.FloatField(blank=True, null=True)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
